# This file was generated by GoReleaser. DO NOT EDIT.
cask "gopull" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "839fb935061be4575f8cc07cd7e6f4f9e62043bd100dc143f1f7b406b409dd28"
      url "https://github.com/d0mkaaa/gopull/releases/download/v#{version}/gopull_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d39ef17310aa1639ad070cd039cace684414609e04b03507e7545ce6eb1cc991"
      url "https://github.com/d0mkaaa/gopull/releases/download/v#{version}/gopull_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ae5f5df947d4cc7f35435390e7e10ae480a5c54c6f9f7d3af62a517afd91fe9b"
      url "https://github.com/d0mkaaa/gopull/releases/download/v#{version}/gopull_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "440e7f645f47a431018696ccd28cd9a2d7f14be710a099e76fe6c901a142f076"
      url "https://github.com/d0mkaaa/gopull/releases/download/v#{version}/gopull_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gopull"
  desc "A terminal HTTP client. Send requests, manage collections, inspect responses."
  homepage "https://github.com/d0mkaaa/gopull"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gopull"

  # No zap stanza required

  caveats <<~EOS
    gopull is not signed with an Apple Developer ID.
    If macOS blocks the binary on first run, remove the quarantine flag:
      xattr -d com.apple.quarantine "$(which gopull)"
  EOS
end
