# This file was generated by GoReleaser. DO NOT EDIT.
cask "gopull" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "84d20af77de096c0f3f5cb016096febce764b5da8b8b3644132673225570d433"
      url "https://github.com/d0mkaaa/gopull/releases/download/v#{version}/gopull_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ba8d3dd56d5323589d8640aa58f11d00c01892f52bda8ff01d6681d82a60c1fa"
      url "https://github.com/d0mkaaa/gopull/releases/download/v#{version}/gopull_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e18894be545e4817823ecb81de3d57ffdf075dd5f9a827a95d85f00690f36dc7"
      url "https://github.com/d0mkaaa/gopull/releases/download/v#{version}/gopull_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3f95d6014a59d5972d2730d933ae45cfcdb894c636488cebd0835385390563c6"
      url "https://github.com/d0mkaaa/gopull/releases/download/v#{version}/gopull_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gopull"
  desc "A terminal HTTP client. Send requests, manage collections, inspect responses."
  homepage "https://github.com/d0mkaaa/gopull"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gopull"

  # No zap stanza required

  caveats <<~EOS
    gopull is not signed with an Apple Developer ID.
    If macOS blocks the binary on first run, remove the quarantine flag:
      xattr -d com.apple.quarantine "$(which gopull)"
  EOS
end
