# This file was generated by GoReleaser. DO NOT EDIT.
cask "gopull" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "9d1a5adc1252683c7c52b136bd9b9dd37ca3d38ad8029255487c844097046f3e"
      url "https://github.com/d0mkaaa/gopull/releases/download/v#{version}/gopull_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "bcdb16086c64ca14470963e9b418ac588aca143d4de121b8fc169117f97ce4d8"
      url "https://github.com/d0mkaaa/gopull/releases/download/v#{version}/gopull_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d7c7aaf624ce73704bb2077d8b658a8b1b7afe6fc3d90f9a950e6ea85f60e4e5"
      url "https://github.com/d0mkaaa/gopull/releases/download/v#{version}/gopull_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0505c1047b56d6f621b8bee193673643443600a49d8ddf33b6fe19c8c5632ba3"
      url "https://github.com/d0mkaaa/gopull/releases/download/v#{version}/gopull_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gopull"
  desc "A terminal HTTP client. Send requests, manage collections, inspect responses."
  homepage "https://github.com/d0mkaaa/gopull"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gopull"

  # No zap stanza required

  caveats <<~EOS
    gopull is not signed with an Apple Developer ID.
    If macOS blocks the binary on first run, remove the quarantine flag:
      xattr -d com.apple.quarantine "$(which gopull)"
  EOS
end
